hmcts/hmc-operational-reports-runner

src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapper.java
src/main/java/uk/gov/hmcts/reform/hmc/model/HearingRequestForCsv.java
src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapperTest.java

https://tools.hmcts.net/jira/browse/HMAN-390
Show hearing status 'LISTED', 'UPDATE REQUESTED', 'UPDATE SUBMITTED'
```
[ ] Yes
[x] No
```

HMAN-390 return hearing status not AWAITING_ACTUALS

---

charts/hmc-operational-reports-runner/values.yaml

HMAN-389 enable keyVault

---

charts/hmc-operational-reports-runner/values.yaml

HMAN-389 update from java to job

---

charts/hmc-operational-reports-runner/Chart.yaml

HMAN-389 bump chart version

---

src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapper.java

HMAN-389 bug fix to handle null

---

charts/hmc-operational-reports-runner/values.yaml
src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapper.java
src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsHelper.java
src/main/resources/application.yaml

HMAN-389 bug fix to handle null for endDate and also make configDays configurable

---

charts/hmc-operational-reports-runner/Chart.yaml
charts/hmc-operational-reports-runner/values.yaml
config/owasp/suppressions.xml

fix master build

---

.github/workflows/dependency-check.yml
Jenkinsfile_CNP
build.gradle
charts/hmc-operational-reports-runner/Chart.yaml
charts/hmc-operational-reports-runner/values.preview.template.yaml
config/owasp/suppressions.xml
gradle/suppress.gradle

https://tools.hmcts.net/jira/browse/HMAN-494
Add suppressCves task
```
[ ] Yes
[ ] No
```

HMAN-494 Add suppressCves task

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-508
Fix CVEs in hmc-operational-reports-runner repo.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

HMAN-508: Fix CVEs in hmc-operational-reports-runner repo

---

src/integrationTest/resources/application-itest.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/HMAN-509
Remove discoveryComposite from health endpoint
```
[X] Yes (tests expecting discoveryComposite from the health endpoint may fail)
[] No
```

HMAN-509 Remove discoveryComposite from health endpoint

---

charts/hmc-operational-reports-runner/Chart.yaml

https://tools.hmcts.net/jira/browse/HMAN-521
Update 'chart'job' to latest : Chart.yaml
```
[ ] Yes
[X] No
```

Update 'chart'job' to latest : Chart.yaml

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-4949
Fix - Versions below java-logging: 6.0.1
```
[ ] Yes
[ ] No
```

CCD-4949:Fix - Versions below java-logging: 6.0.1

---

charts/hmc-operational-reports-runner/Chart.yaml
src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapper.java
src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapperTest.java

https://tools.hmcts.net/jira/browse/HMAN-600
```
[ ] Yes
[ ] No
```

HMAN-600 fix formatting of ccd case reference

---

charts/hmc-operational-reports-runner/Chart.yaml

CCD-5133 Update Chart.yaml

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-677
Fix CVE-2024-1597
```
[ ] Yes
[x] No
```

HMAN-677 fix CVE-2024-1597

---

docker-compose.yml

https://tools.hmcts.net/jira/browse/HMAN-396
Add to ccd-docker. 
Provide proper name for docker image
```
[ ] Yes
[x] No
```

HMAN-396 provide proper name for docker image

---

Dockerfile
charts/hmc-operational-reports-runner/Chart.yaml
charts/hmc-operational-reports-runner/values.yaml
lib/applicationinsights.json

Fix appinsights 

---

src/main/java/uk/gov/hmcts/reform/hmc/appinsights/AppInsightsConfiguration.java

Add AppInsightsConfiguration.java

---

charts/hmc-operational-reports-runner/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart version

---

build.gradle

https://tools.hmcts.net/jira/browse/CME-509
```
[ ] Yes
[ ] No
```

CME-509: Replace jitpack
